version: "3.8"
services:
  backend:
    build:
      context: .
      target: runner
    ports:
      - 8080:8080
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app
