version: "3.8"
services:
  backend:
    build:
      context: .
      target: runner
    ports:
      - ${PORT}:${PORT}
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app
    environment:
      - PORT=${PORT}
      - APP_ENV=${APP_ENV}
