version: "3.8"
services:
  backend:
    container_name: backend_development
    build:
      context: .
      target: dev
    ports:
      - ${PORT}:${PORT}
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app
    environment:
      - PORT=${PORT}
      - APP_ENV=${APP_ENV}
      - FE_URL=${FE_URL}
